<?php
require_once '../../controller/ReclamationController.php';
require_once '../../Model/Reclamation.php';
require_once '../../config/database.php';

header('Content-Type: application/json');

try {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        throw new Exception('Méthode non autorisée');
    }

    // Récupérer et valider les données du formulaire
    $nomprenom = $_POST['nomprenom'] ?? '';
    $email = $_POST['email'] ?? '';
    $nomfilm = $_POST['nomfilm'] ?? '';
    $type_rec = $_POST['type_rec'] ?? '';
    $detail = $_POST['detail'] ?? '';
    $reponse_rec = ''; // Initial empty response

    // Validation
    if (empty($nomprenom) || empty($email) || empty($nomfilm) || empty($type_rec) || empty($detail)) {
        throw new Exception('Tous les champs sont requis');
    }

    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        throw new Exception('Format d\'email invalide');
    }

    // Créer une nouvelle réclamation
    $reclamation = new Reclamation(
        $nomprenom,
        $email,
        $nomfilm,
        $type_rec,
        $detail,
        $reponse_rec,
        null // id_rec will be generated by the database
    );

    // Sauvegarder la réclamation
    $controller = new ReclamationController();
    $result = $controller->addReclamation($reclamation);

    // Décoder la réponse JSON du contrôleur
    $response = json_decode($result, true);
    
    if ($response === null) {
        throw new Exception('Erreur lors du traitement de la réponse');
    }

    echo $result; // Le contrôleur renvoie déjà du JSON formatté

} catch (Exception $e) {
    http_response_code(400);
    echo json_encode([
        'success' => false,
        'message' => $e->getMessage()
    ]);
}